version: '3'
networks:
  groceryshop:
    external: true
volumes:
  db:
    driver:
      local
services:
  products:
    container_name: products
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - ${SERVER_PORT}:3000
    env_file:
      - .env
    networks:
      - groceryshop
    external_links:
      - auth
      - authredis
      - authdb
    environment:
      NODE_ENV: development
      MYSQL_HOST: authdb
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: grocery123
      MYSQL_USER: root
      MYSQL_PASSWORD: grocery123
      MYSQL_DATABASE: products

  productredis:
    container_name: productredis
    image: redis:alpine
    ports:
      - 6370:6379
    networks:
      - groceryshop
    volumes:
      - "./data/redis:/data"