version: '3'
networks:
  groceryshop:
    external: true
volumes:
  db:
    driver:
      local
services:
  product:
    container_name: product
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - ${SERVER_PORT}:3000
    env_file:
      - .env
    networks:
      - groceryshop
    external_links:
      - auth
      - authredis
      - authdb

  productredis:
    container_name: productredis
    image: redis:alpine
    ports:
      - 6370:6379
    networks:
      - groceryshop
    volumes:
       - "./data/redis:/data"
  productdb:
    image: mysql:5.7
    container_name: productdb
    networks:
      - groceryshop
    ports:
      - "3308:3306"
    volumes:
      - "./data:/docker-entrypoint-initdb.d"
      - "db:/var/lib/mysql"
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE_NAME}
