version: '3'
networks:
  groceryshop:
    external: true
volumes:
  db:
    driver:
      local
services:
  product:
    container_name: product
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      domain: ${DOMAIN}
    restart: always
    volumes:
      - ./:/app
    ports:
      - ${SERVER_PORT}:3000
    env_file:
      - .env
    networks:
      - groceryshop
    external_links:
      - auth
      - authredis
      - productdb

  productdb:
    image: mysql:5.7
    container_name: productdb
    networks:
      - groceryshop
    ports:
      - "3308:3306"
    volumes:
      - "./data:/docker-entrypoint-initdb.d"
      - "db:/var/lib/mysql"
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE_NAME}

  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - groceryshop
    environment:
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_USER: user
